# Generated by Django 3.1.7 on 2021-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struct',
            name='divisionClauseDocLinkFileNames',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
