# Generated by Django 3.1.7 on 2021-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_common_filinfo_repinfo_uchredlaw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struct',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
