# Generated by Django 3.1.7 on 2021-03-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20210308_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='regDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
