# Generated by Django 3.1.7 on 2021-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_auto_20210314_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='additionalInformation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='common',
            name='workTime',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='filinfo',
            name='workTimeFil',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='repinfo',
            name='workTimeRep',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='uchredlaw',
            name='addressUchred',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
